<a href="https://colab.research.google.com/github/Aggarwalmansi/GENAI/blob/main/Lab1(Numpy_and_Pandas).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [ ]:
a2= np.array([[1,2],[3,4],[5,6],[7,8]])
a2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
a3 = np.array([1,2,3,4,5,6])
a3_reshape = a3.reshape(2,3)
a3_reshape

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
one_matrix = np.ones((2,2))
one_matrix

array([[1., 1.],
       [1., 1.]])

In [ ]:
int_matrix = np.ones((2,2), dtype='int')
int_matrix

array([[1, 1],
       [1, 1]])

In [ ]:
zero_matrix = np.zeros((2,2))
zero_matrix

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.full((2,2),5)

array([[5, 5],
       [5, 5]])

In [ ]:
one1 = np.ones((4,4))
reone1 = one1.reshape(2,8)
reone1


array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.random.randint(0,100,(3,3))

array([[97, 75, 28],
       [94, 75, 14],
       [78, 17, 25]])

In [ ]:
np.random.randint(-5,60,(4,4))


array([[55, 13, 27, 47],
       [34, 42, 45, 38],
       [51,  4,  8, 13],
       [ 9, 30,  6, 23]])

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
a1 = np.array([[1,2],[3,4],[5,6]])
a2 = np.array([[9,10],[11,14] ,[1,2]])
r2 = a1 + a2
r2

array([[10, 12],
       [14, 18],
       [ 6,  8]])

In [ ]:
a1 = np.array([1,2,3])

In [ ]:
a1*2

array([2, 4, 6])

In [ ]:
l1 = np.array([1,2,3])
l2 = np.array([4,5,6])
r = l1+l2
r

array([5, 7, 9])

In [ ]:
import pandas as pd


In [ ]:
S =pd.Series([1,2,3,4,5])
S

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
S.iloc[0]

np.int64(1)

iloc - internal location

In [ ]:
S = pd.Series([4,5,6,7], index = ['a','b','c','d'])
# this is external indexing
S

a    4
b    5
c    6
d    7
dtype: int64

In [ ]:
S.iloc[0]


np.int64(4)

In [ ]:
S.loc['a']

np.int64(4)

In [ ]:
S.iloc[0:2]

a    4
b    5
dtype: int64

In [ ]:
S + 2

a    6
b    7
c    8
d    9
dtype: int64

In [ ]:
S2 = pd.Series([1,2,3,4,5,6,7,8,9,10])
S2*10


0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int64

In [ ]:
df = pd.DataFrame({"Name":["Anant","Ram","Balaji"],"Age":[12,35,21]})
df

Name  Age
0   Anant   12
1     Ram   35
2  Balaji   21

In [ ]:
df1 = pd.DataFrame({"Name":["ananya","Isha","Tanisha","Yashi"],"City":["Punjab","bahrobad","Up","Rajasthan"]})
df1

Name       City
0   ananya     Punjab
1     Isha   bahrobad
2  Tanisha         Up
3    Yashi  Rajasthan

from matplotlib import pyplot as plt
import seaborn as sns
df1.groupby('Name').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
df1.groupby('City').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['City'].value_counts()
    for x_label, grp in df1.groupby('Name')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('Name')
_ = plt.ylabel('City')

In [ ]:
df1.Name

0     ananya
1       Isha
2    Tanisha
3      Yashi
Name: Name, dtype: object

In [ ]:
df1[['Name','City']]

Name       City
0   ananya     Punjab
1     Isha   bahrobad
2  Tanisha         Up
3    Yashi  Rajasthan

In [ ]:
df.loc[df['Age']>20]

Name  Age
1     Ram   35
2  Balaji   21