<a href="https://colab.research.google.com/github/Aggarwalmansi/GENAI/blob/main/sentiment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN , Dense , Embedding


In [2]:
train_sentence = [
    'The movie was truly amazing and exciting',
    'I absolutely loved the delicious food',
    'This is the best day ever',
    'The service was terrible and very slow',
    'I really hated the boring movie',
    'This is the worst experience ever'
]

In [3]:
train_labels = np.array([1,1,1,0,0,0])

In [4]:
tokenizer = Tokenizer(num_words=100, oov_token='<OOV>')
tokenizer.fit_on_texts(train_sentence)
sequence = tokenizer.texts_to_sequences(train_sentence)


In [5]:
max_length = 8
padded_data  = pad_sequences(sequence, maxlen=max_length, padding='post')


In [6]:
print("Word Index:",tokenizer.word_index)
print("Padded Data:\n",padded_data)


Word Index: {'<OOV>': 1, 'the': 2, 'movie': 3, 'was': 4, 'and': 5, 'i': 6, 'this': 7, 'is': 8, 'ever': 9, 'truly': 10, 'amazing': 11, 'exciting': 12, 'absolutely': 13, 'loved': 14, 'delicious': 15, 'food': 16, 'best': 17, 'day': 18, 'service': 19, 'terrible': 20, 'very': 21, 'slow': 22, 'really': 23, 'hated': 24, 'boring': 25, 'worst': 26, 'experience': 27}
Padded Data:
 [[ 2  3  4 10 11  5 12  0]
 [ 6 13 14  2 15 16  0  0]
 [ 7  8  2 17 18  9  0  0]
 [ 2 19  4 20  5 21 22  0]
 [ 6 23 24  2 25  3  0  0]
 [ 7  8  2 26 27  9  0  0]]


In [7]:
model = Sequential()

In [8]:
model.add(Embedding(input_dim=100, output_dim=8))

In [9]:
model.add(SimpleRNN(16))

In [10]:
model.add(Dense(1,activation='sigmoid'))

In [12]:
model.compile(loss = 'binary_crossentropy',optimizer = 'adam', metrics = ['accuracy'])

In [13]:
model.fit(padded_data , train_labels,epochs=50)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.3333 - loss: 0.6979
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.3333 - loss: 0.6923
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5000 - loss: 0.6869
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.5000 - loss: 0.6815
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6762
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6667 - loss: 0.6708
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6667 - loss: 0.6654
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.6667 - loss: 0.6600
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6667 - loss: 0.6544
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6667 - loss: 0.6486
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6667 - loss: 0.6427
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.6667 - loss: 0.6365
Epo

In [14]:
test_text = ["I loved the exciting movie","The food was terrible"]
test_seq = tokenizer.texts_to_sequences(test_text)
test_pad = pad_sequences(test_seq,maxlen=max_length,padding='post')

In [15]:
print("\n--- Test Results")


--- Test Results


In [16]:
preds = model.predict(test_pad)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step


In [17]:
print("Presdictions:",preds)

Presdictions: [[0.57409155]
 [0.5034033 ]]
